### PR TITLE
Feature/pod logs

### PR DESCRIPTION
**Pull request by pcm32**
Allows to retrieve logs for a Pod, in the same way as it is provided by `kubectl logs pod/<pod-name>`. Current implementation resides in the Pod object, although an alternative would be to have it done from the Query object. Should resolve issue #36 .

### CODE REVIEW

**Comment by Copper-Head** [comment]
I wonder if there's a way to make your solution more general. There are other operations (such as `exec`, `attach`) that basically use the same url creation mechanism as `logs`. So I wonder if it's a better idea to try to come up with a general solution for "operations on pods" and use that to instantiate the particular operations...

Concretely, it may be more prudent to tweak the `APIObject`'s `api_kwargs` function so that it accepts custom URL continuations. Then inside `get_logs`, `attach` __and Co__ we can simply pass those url continuations, along with options of course.

I hope that was clear, please let me know otherwise. And of course feedback from @brosner is most welcome on this.

**Comment by brosner** [comment]
I agree @Copper-Head. Introducing a `pod` kwarg to `HTTPClient.get_kwargs` isn't ideal. There are other cases where we may end up doing something similar causing a mess. `APIObject.api_kwargs` is a better place and we can later mix it up with some methods on children classes that are specific for each type of object.

We should break this out into its own issue and track it first. Doing so will make this PR dependent on the solution there, but it's worth it for the better design in pykube. I have some more thoughts on this topic, but would like to discuss on that issue. Do you mind getting that effort started @Copper-Head?

**Comment by Copper-Head** [comment]
Sure thing! I actually think I can produce something that exemplifies my thinking over this weekend. Should I just open a new PR, or would you rather we discuss stuff first in an issue (in which case I'll simply post my proposed changes as code snippets in a comment)?

**Comment by brosner** [comment]
@Copper-Head a PR would be fine. We can discuss the change there and get it rolled in quickly. Thank you!

**Comment by pcm32** [comment]
Sorry @Copper-Head & @brosner, today was quite busy and didn't have time to get into this discussion. I'm happy to add some changes here if you explain a bit more the idea. If you want to otherwise take it to another PR for this same functionality (get_logs), can I ask please that at least you keep all the options for the logs that I wrote into this? so that I can continue to use them on the code where I'm using pykube. Please keep me in the loop if you do a new PR, I'm currently using this and the unauthenticated functionality from a branch of my own (pip installing from there), but I would like to move back to the official installations once these functionalities are incorporated.

**Comment by brosner** [comment]
@pcm32 this PR doesn't need to change. @Copper-Head and I were discussing specifically the URL generation parts. Once we've finalized that we can update `get_logs` to work with it. Nothing to worry about :-)

**Comment by Copper-Head** [comment]
I *do* have one small question regarding the method naming. @pcm32 what do you think of renaming `get_logs` to `logs`? I imagine new users of the client will be coming from `kubectl` and it would probably make their life easier if the method names we provide are easy to map onto corresponding `kubectl` commands. This wouldn't be a major change on your end, but I think it would simplify life for folks new to the library.

**Comment by brosner** [comment]
@Copper-Head I was going to make that exact suggestion when I reviewed this code. :-)

**Comment by pcm32** [comment]
@Copper-Head agreed, `logs` is a better method name. Will change it.

**Comment by brosner** [comment]
I'd like to get this merged for the next pykube release. @pcm32 can you update it to pass and resolve conflicts? Thanks!

**Comment by pcm32** [comment]
Hi,

I have been looking at this for a while today, problem is here in `objects.py`:

```python
        if since_seconds is not None and since_time is None:
            params["sinceSeconds"] = int(since_seconds)
```
on both lines column 18, giving a PEP8 `E127 continuation line over-indented for visual indent`. However, as much as I reformat the line, I keep getting PEP issues on pycharm. Any suggestions on how I should reformat the line so that it doesn't complain? Thanks!

**Comment by pcm32** [comment]
Hi @brosner, after the last commit for fixing PEP warnings, I'm getting branch conflicts. Could you take a look at this? Thanks.

**Comment by brosner** [comment]
I have created a new branch, pod-logs, which has corrected the conflict and updated for the changes made by @Copper-Head. Can someone give it test and see if everything works? If so, then I'll merge it!

**Comment by Copper-Head** [comment]
I won't have time to test this until the last week of July at the earliest, I'm afraid.

**Comment by pcm32** [comment]
Hi there, apologies for the delay, I have tried it and it fails:

```python
import operator
import pykube
api = pykube.HTTPClient(pykube.KubeConfig.from_file("/Users/<user>/.kube/config"))  # change this to fit your install
pods = pykube.Pod.objects(api).filter(selector="<your_selector>") # change this to fit your case
podG = pykube.Pod(api, pods.response['items'][0])
logs = podG.logs()
```

produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/.test-pykubelogs/lib/python2.7/site-packages/pykube/objects.py", line 225, in logs
    r = self.api.get(**kwargs)
  File "/private/tmp/.test-pykubelogs/lib/python2.7/site-packages/pykube/http.py", line 125, in get
    return self.session.get(*args, **self.get_kwargs(**kwargs))
  File "/private/tmp/.test-pykubelogs/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
TypeError: request() got an unexpected keyword argument 'operation'
```

When redoing the same with my [branch](https://github.com/pcm32/pykube/tree/feature/allMergedFeatures) it produces the log output correctly as a string, without the error.

**Comment by pcm32** [comment]
@brosner I have made the changes necessary for the logs method to play nicely with the underlying changes suggested later that were conflicting with it. I have tested it like this:

```
import operator
import pykube

api = pykube.HTTPClient(pykube.KubeConfig.from_file("<your-config-file>"))
pods = pykube.Pod.objects(api).filter(selector="<your-pod>")
pod_obj = pods.response['items'][0]
pod = pykube.Pod(api, pod_obj)
print pod.logs(timestamps=True)
```

...and works fine!

**Comment by tobegit3hub** [comment]
I have test @pcm32 's branch and it works like a charm. I can view the logs of pods, just like `kubectl logs $pod`.

Thanks for your contribution and looking forward to merge in master.

**Pull request merged**
